theme: jekyll-theme-modernist
description: [ordina pizze e sfotte la gente]
show_downloads: [true]
google_analytics: [UA-113094486-1]
github:
  zip_url: https://codeload.github.com/andrimanna/ilbuonmatteobot/zip/master
